[package]
name = "zero2prod"
version = "0.1.0"
authors = ["Totti <tottexi97131@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.1.0"
actix-rt = "1.1.1"
